# yaml-language-server: $schema=../../../../schemas/agent_config_schema.yaml
AgentConfiguration:
  agent_name: rag_agent
  description: RAG Agent configuration
  config_version: '9.1'
  application_version: '1.0'
  application_name: rag_llmops_workshop
  deployment:
    name: gpt-4o-mini
    model_name: gpt-4o-mini
    model_version: '2024-08-01'
    endpoint: https://openai-australia-east-303474.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-10-01-preview
    openai_api_version: 2024-10-01-preview
  model_parameters:
    temperature: 0.5
    seed: 42
  retrieval:
    parameters:
      search_type: hybrid
      top_k: 5
      index_name: micirosoft-tech-stack-index-0
      index_semantic_configuration_name: vector-llmops-workshop-index-semantic-configuration
    deployment:
      model_name: text-embedding-ada-002
      model_version: '2024-08-01'
      openai_api_version: 2024-10-01-preview
      name: text-embedding-ada-002
      endpoint: https://openai-australia-east-303474.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-05-15
  intent_system_prompt: "Your task is to extract the user\u2019s intent by reformulating\
    \ their latest question into a standalone query that is understandable without\
    \ prior chat history. Analyze the conversation to identify any contextual references\
    \ in the latest question, and incorporate necessary details to make it self-contained.\
    \ Ensure the reformulated question preserves the original intent. Do not provide\
    \ an answer; only return the reformulated question. For example, if the latest\
    \ question is \u2018What about its pricing?\u2019 and the chat history discusses\
    \ Microsoft Azure, reformulate it to \u2018What is the pricing of Microsoft Azure?\u2019"
  chat_system_prompt: "You are a knowledgeable assistant specializing only in technology\
    \ domain. Deliver concise and clear answers, emphasizing the main points of the\
    \ user\u2019s query. Your responses should be based exclusively on the context\
    \ provided in the prompt; do not incorporate external knowledge. If the provided\
    \ context is insufficient to answer the question, request additional information.\n\
    \n<context>\n{context}\n</context>"
  human_template: 'question: {input}'
