# yaml-language-server: $schema=../schemas/rag_agent_config_schema.yaml
AgentConfiguration:
  description: "RAG Agent configuration"
  config_version: 1.1
  application_version: "1.0"   
  application_name: "rag_llmops_workshop" 
  
  agent_name: "rag_agent"
  model_name: "gpt-4o-mini"
  model_version: "2024-08-01"

  openai_api_version: "2024-10-01-preview"

  #model_deployment: "gpt-4o-3"
  #model_deployment_endpoint: "https://openai-australia-east-303474.openai.azure.com/openai/deployments/gpt-4o-3/chat/completions?api-version=2024-08-01-preview"
  
  #model_deployment: "gpt-35-turbo"
  #model_deployment_endpoint: "https://openai-australia-east-303474.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-08-01-preview"

  model_deployment: "gpt-4o-mini"
  model_deployment_endpoint: "https://openai-australia-east-303474.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-10-01-preview"
  
  retrieval: 
      search_type: "hybrid"
      top_k: 5
      embedding_endpoint: "https://openai-australia-east-303474.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-05-15"
      embedding_deployment: "text-embedding-ada-002"
      index_name: "micirosoft-tech-stack-index-0"
      #index_name: "xx-index11"
      index_semantic_configuration_name: "vector-llmops-workshop-index-semantic-configuration"
  model_parameters:
    temperature: 0.0
    seed: 42
  intent_system_prompt: > 
        Your task is to extract the user’s intent by reformulating their latest question into a standalone query that is understandable without prior chat history. 
        Analyze the conversation to identify any contextual references in the latest question, and incorporate necessary details to make it self-contained. 
        Ensure the reformulated question preserves the original intent. Do not provide an answer; only return the reformulated question. 
        For example, if the latest question is ‘What about its pricing?’ and the chat history discusses Microsoft Azure, reformulate it to ‘What is the pricing of Microsoft Azure?’

  chat_system_prompt: > 
        You are a knowledgeable assistant specializing only in technology domain. 
        Deliver concise and clear answers, emphasizing the main points of the user’s query.
        Your responses should be based exclusively on the context provided in the prompt; do not incorporate external knowledge.
        If the provided context is insufficient to answer the question, request additional information.
            
        <context>
        {context}
        </context>"

  human_template: "question: {input}"
  
